Repository graph-gophers/graphql-go, pull requests merged in 2023-02, with the labels that each got.

#569 Conditionally allow introspection
  examples_test.go
  graphql.go
  internal/exec/selected/selected.go
Labels: enhancement

#575 Refactor useFieldResolvers
  graphql.go
  internal/exec/resolvable/meta.go
  internal/exec/resolvable/resolvable.go
  types/schema.go
Labels: bug

#577 Add string descriptions example
  examples_test.go
Labels: documentation

#573 Refactor field resolution closer to schema types
  internal/exec/exec.go
  internal/exec/resolvable/resolvable.go
  internal/exec/selected/selected.go
Labels: enhancement

#585 Allow directives on schema
  ast/schema.go
  examples_test.go
  internal/schema/schema.go
  internal/schema/schema_internal_test.go
Labels: bug, enhancement

#589 Allow fragment on interface
  graphql_test.go
  internal/exec/resolvable/meta.go
  internal/exec/resolvable/resolvable.go
  internal/exec/selected/selected.go
Labels: bug

#583 Add Validating Directives
  directives/visitor.go
  example/directives/authorization/README.md
  example/directives/authorization/authorization.go
  example_directives_test.go
  graphql_test.go
  internal/exec/exec.go
  internal/exec/resolvable/resolvable.go
  internal/exec/selected/selected.go
  internal/exec/validate.go
Labels: enhancement

#596 Add graphql reflect tag
  examples_test.go
  graphql_test.go
  internal/exec/resolvable/resolvable.go
  introspection_test.go
Labels: bug, enhancement
